Repository seeus-dev/seeus-backend, pull requests merged in 2020-04, with the labels that each got.

#8 Set up Flask and Postgres with docker-compose
  .env.example
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  requirements.txt
  scripts/psql
  scripts/setup
  scripts/start
  scripts/stop
  scripts/webshell
  src/app.py
Labels: enhancement, new feature

#9 Added database tables and configured docker-compose.yml
  docker-compose.yml
  requirements.txt
  schemas/config.sql
  scripts/psql
  src/database.py
Labels: new feature

#11 Create config object to hold environmental variable configuration values
  .env.example
  src/config.py
  src/database.py
Labels: refactor

#15 Create Database class abstraction and data model classes
  src/app.py
  src/blueprints/dispatcher.py
  src/blueprints/mobile.py
  src/database.py
  src/models.py
  src/query.py
Labels: enhancement, refactor
